#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
xset r rate 300 50 &    # Speed xrate up
dunst --config $HOME/.config/dunst/dunstrc &
eww daemon &
picom --config $HOME/.config/picom/picom.conf &
#xcompmgr &
hsetroot -fill "$HOME/Pictures/Wallpapers/clouds.jpg"
sh $HOME/.config/polybar/launch.sh
#sudo protonvpn c --cc US
#sudo wondershaper -a wlp0s29f7u1 -d 1500 -u 200
#pgrep bspswallow || bspswallow &

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         3
bspc config window_gap           18

bspc config top_padding          36
bspc config bottom_padding       0

bspc config normal_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config focused_border_color "#282828"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bpsc rule -a custom-brave desktop=^1
bspc rule -a discord desktop=^2
bspc rule -a nvim desktop=^3
bspc rule -a Thunar desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Zathura state=tiled
